version: '2'
services:
  frontend:
    build: ./frontend/
    image: videos-frontend-service3
    container_name: videos-frontend-service3
    ports:
      - "80:80"
    depends_on:
      - backend
      - web_server
  web_server:
    image: nginx
    container_name: videos-web-server3
    restart: always
    expose:
      - "80/tcp"
    ports:
      - "8080:80"
    volumes:
      - ./volumes/public:/usr/share/nginx/html:ro
    environment:
      - NGINX_PORT=80
  db:
    image: mysql:8.0.21
    container_name: videos-db-service3
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=videos-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user-password
      - MYSQL_ROOT_PASSWORD=root-password
    expose:
      - "3306"
      - "33060"
    volumes:
      - ./volumes/data:/var/lib/mysql
    networks:
      - videos_backend

  backend:
    build: ./backend/
    image: videos-backend-service3
    container_name: videos-backend-service3
    environment:
      - PORT=3000
      - DATABASE_NAME=videos-db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user-password
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - WAIT_HOSTS=db:3306
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - videos_backend
    depends_on:
      - db
    volumes:
      - ./volumes/public/videos:/videos
      - ./volumes/public/images:/images

networks:
  videos_backend:
    driver: bridge
